### PR TITLE
LIBHYDRA-161. Switch to omniauth-cas gem.

### PR DESCRIPTION
**Pull request by mohideen**
https://issues.umd.edu/browse/LIBHYDRA-161

### CODE REVIEW

**Comment by peichman-umd** [comment]
@mohideen When I go to http://localhost:3000, it redirects me to http://localhost:3000/auth/:provider and then responds with the error **No route matches [GET] "/auth/:provider"**.

**Comment by peichman-umd** [comment]
@mohideen It looks like something in the routes.rb probably needs fixing.

**Comment by peichman-umd** [comment]
@mohideen I also get a "Not Authorized" error when I follow the "Log Out" link (http://localhost:3000/logout)

**Comment by mohideen** [comment]
@peichman-umd Fixed it. Please test again.

**Pull request merged**
